{
  "apiVersion": "doslab.io/v1",
  "kind": "Frontend",
  "metadata": {
    "name": "all-routes"
  },
  "spec": {
    "data": [{
      "menuIcon": "el-icon-Monitor",
      "kind": "云主机",
      "pid": 0,
      "updateTime": "2022-09-19 17:22:25",
      "params": "",
      "isShow": 1,
      "isCache": 1,
      "isDisable": 0,
      "component": "article/lists/index",
      "createTime": "2022-04-19 12:16:05",
      "paths": "workbench",
      "menuType": "C",
      "perms": "common:index:console",
      "id": 1,
      "selected": "",
      "menuSort": 50,
      "listname": "Node",
      "tablename": "node"
    },
      {
        "menuIcon": "el-icon-ChatDotSquare",
        "kind": "云盘",
        "pid": 703,
        "updateTime": "2022-09-20 15:17:00",
        "params": "",
        "isShow": 1,
        "isCache": 1,
        "isDisable": 0,
        "component": "article/lists/index",
        "createTime": "2022-08-29 15:22:23",
        "paths": "lists",
        "menuType": "C",
        "perms": "article:list",
        "id": 704,
        "selected": "",
        "menuSort": 49,
        "listname": "apps.ReplicaSet",
        "tablename": "apps.replicaset"
      },
      {
        "menuIcon": "el-icon-CollectionTag",
        "kind": "镜像",
        "pid": 703,
        "updateTime": "2022-09-19 17:02:17",
        "params": "",
        "isShow": 1,
        "isCache": 1,
        "isDisable": 0,
        "component": "article/lists/index",
        "createTime": "2022-08-29 15:46:58",
        "paths": "column",
        "menuType": "C",
        "perms": "article:cate:list",
        "id": 705,
        "selected": "",
        "menuSort": 48,
        "listname": "Pod",
        "tablename": "pod"
      },
      {
        "menuIcon": "el-icon-Lock",
        "kind": "权限管理",
        "pid": 0,
        "updateTime": "2022-09-08 16:36:41",
        "params": "",
        "isShow": 1,
        "isCache": 0,
        "isDisable": 0,
        "component": "",
        "createTime": "2022-04-19 12:16:05",
        "children": [{
          "menuIcon": "local-icon-wode",
          "kind": "管理员",
          "pid": 100,
          "updateTime": "2022-09-16 12:10:04",
          "params": "",
          "isShow": 1,
          "isCache": 1,
          "isDisable": 0,
          "component": "permission/admin/index",
          "createTime": "2022-04-19 12:16:05",
          "paths": "admin",
          "menuType": "C",
          "perms": "system:admin:list",
          "id": 101,
          "selected": "",
          "menuSort": 0
        },
          {
            "menuIcon": "el-icon-Female",
            "kind": "角色管理",
            "pid": 100,
            "updateTime": "2022-09-16 12:10:51",
            "params": "",
            "isShow": 1,
            "isCache": 1,
            "isDisable": 0,
            "component": "permission/role/index",
            "createTime": "2022-04-19 12:16:05",
            "paths": "role",
            "menuType": "C",
            "perms": "system:role:list",
            "id": 110,
            "selected": "",
            "menuSort": 0
          }
        ],
        "paths": "permission",
        "menuType": "M",
        "perms": "",
        "id": 100,
        "selected": "",
        "menuSort": 44
      },
      {
        "menuIcon": "local-icon-keziyuyue",
        "kind": "用户设置",
        "pid": 500,
        "updateTime": "2022-09-16 12:12:50",
        "params": "",
        "isShow": 1,
        "isCache": 0,
        "isDisable": 0,
        "component": "",
        "createTime": "2022-09-06 17:10:07",
        "children": [{
          "menuIcon": "",
          "kind": "用户设置",
          "pid": 724,
          "updateTime": "2022-09-16 15:10:25",
          "params": "",
          "isShow": 1,
          "isCache": 0,
          "isDisable": 0,
          "component": "setting/user/setup",
          "createTime": "2022-09-06 17:12:35",
          "paths": "setup",
          "menuType": "C",
          "perms": "setting:user:detail",
          "id": 725,
          "selected": "",
          "menuSort": 0
        },
          {
            "menuIcon": "",
            "kind": "登录注册",
            "pid": 724,
            "updateTime": "2022-09-16 15:11:03",
            "params": "",
            "isShow": 1,
            "isCache": 0,
            "isDisable": 0,
            "component": "setting/user/login_register",
            "createTime": "2022-09-06 17:27:55",
            "paths": "login_register",
            "menuType": "C",
            "perms": "setting:login:detail",
            "id": 726,
            "selected": "",
            "menuSort": 0
          }
        ],
        "paths": "user",
        "menuType": "M",
        "perms": "",
        "id": 724,
        "selected": "",
        "menuSort": 8
      },
      {
        "menuIcon": "",
        "kind": "文章添加/编辑",
        "pid": 703,
        "updateTime": "2022-09-30 11:54:52",
        "params": "",
        "isShow": 0,
        "isCache": 0,
        "isDisable": 0,
        "component": "article/lists/edit",
        "createTime": "2022-09-08 16:31:22",
        "paths": "lists/edit",
        "menuType": "C",
        "perms": "article:add/edit",
        "id": 731,
        "selected": "/article/lists",
        "menuSort": 2
      },
      {
        "menuIcon": "el-icon-EditPen",
        "kind": "开发工具",
        "pid": 0,
        "updateTime": "2022-09-28 11:28:21",
        "params": "",
        "isShow": 1,
        "isCache": 0,
        "isDisable": 0,
        "component": "",
        "createTime": "2022-08-09 14:46:46",
        "children": [{
          "menuIcon": "el-icon-Box",
          "kind": "字典管理",
          "pid": 600,
          "updateTime": "2022-09-15 15:14:47",
          "params": "",
          "isShow": 1,
          "isCache": 0,
          "isDisable": 0,
          "component": "setting/dict/type/index",
          "createTime": "2022-08-09 16:57:16",
          "paths": "dict",
          "menuType": "C",
          "perms": "setting:dict:type:list",
          "id": 515,
          "selected": "",
          "menuSort": 0
        },
          {
            "menuIcon": "",
            "kind": "字典数据管理",
            "pid": 600,
            "updateTime": "2022-09-16 14:20:52",
            "params": "",
            "isShow": 0,
            "isCache": 0,
            "isDisable": 0,
            "component": "setting/dict/data/index",
            "createTime": "2022-08-11 15:29:08",
            "paths": "dict/data",
            "menuType": "C",
            "perms": "setting:dict:data:list",
            "id": 519,
            "selected": "/dev_tools/dict",
            "menuSort": 0
          },
          {
            "menuIcon": "el-icon-DocumentAdd",
            "kind": "代码生成器",
            "pid": 600,
            "updateTime": "2022-08-15 11:01:50",
            "params": "",
            "isShow": 1,
            "isCache": 0,
            "isDisable": 0,
            "component": "dev_tools/code/index",
            "createTime": "2022-08-09 15:09:14",
            "paths": "code",
            "menuType": "C",
            "perms": "gen:list",
            "id": 610,
            "selected": "",
            "menuSort": 0
          },
          {
            "menuIcon": "",
            "kind": "编辑数据表",
            "pid": 600,
            "updateTime": "2022-08-30 15:13:35",
            "params": "",
            "isShow": 0,
            "isCache": 0,
            "isDisable": 0,
            "component": "dev_tools/code/edit",
            "createTime": "2022-08-30 15:12:05",
            "paths": "code/edit",
            "menuType": "C",
            "perms": "gen:editTable",
            "id": 715,
            "selected": "/dev_tools/code",
            "menuSort": 0
          }
        ],
        "paths": "dev_tools",
        "menuType": "M",
        "perms": "",
        "id": 600,
        "selected": "",
        "menuSort": 0
      },
      {
        "menuIcon": "",
        "kind": "用户详情",
        "pid": 712,
        "updateTime": "2022-09-08 17:07:29",
        "params": "",
        "isShow": 0,
        "isCache": 0,
        "isDisable": 0,
        "component": "consumer/lists/detail",
        "createTime": "2022-09-08 17:07:29",
        "paths": "detail",
        "menuType": "C",
        "perms": "user:detail",
        "id": 739,
        "selected": "/consumer/lists",
        "menuSort": 0
      }
    ]
  }
}
