# General configuration
server:
  address: 0.0.0.0
  port: 30308
  servlet:
    context-path: /kubesys

spring:
  datasource:
    auth:
      hikari:
        maximum-pool-size: 3
        minimum-idle: 2
        idle-timeout: 60000
      #jdbcUrl: jdbc:postgresql://133.133.135.134:30306/kubeauth?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&&serverTimezone=Asia/Shang  
      #jdbcUrl: jdbc:postgresql://1.95.7.100:30306/kubeauth?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&&serverTimezone=Asia/Shang
      jdbcUrl: jdbc:postgresql://kube-database.kube-iscas:5432/kubeauth?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&&serverTimezone=Asia/Shang
      username: postgres
      password: onceas
      driverClassName: org.postgresql.Driver
    kube:
      hikari:
        maximum-pool-size: 3
        minimum-idle: 2
        idle-timeout: 60000
      #jdbcUrl: jdbc:postgresql://133.133.135.134:30306/kubestack?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&&serverTimezone=Asia/Shang  
      #jdbcUrl: jdbc:postgresql://1.95.7.100:30306/kubestack?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&&serverTimezone=Asia/Shang
      jdbcUrl: jdbc:postgresql://kube-database.kube-iscas:5432/kubestack?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&&serverTimezone=Asia/Shang
      username: postgres
      password: onceas
      driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate.generate-ddl: true
      hibernate.hbm2ddl.auto: update
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  jackson:
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .html

swagger:
  enabled: true
