{
  "apiVersion": "doslab.io/v1",
  "kind": "Frontend",
  "metadata": {
    "name": "all-routes"
  },
  "spec": {
    "catalogs": [{
      "name": "环境信息",
      "path": "/envInfo"
    },
      {
        "name": "应用管理",
        "path": "/appMgr"
      }
    ],
    "items": [{
      "menuIcon": "el-icon-Monitor",
      "kind": "平台信息",
      "isShow": 1,
      "paths": "/envInfo/basicInfo",
      "menuType": "M",
      "children": [{
        "menuIcon": "el-icon-Monitor",
        "kind": "路测节点",
        "isShow": 1,
        "component": "article/lists/index",
        "paths": "node",
        "menuType": "C",
        "listname": "Node",
        "tablename": "node"
      },
        {
          "menuIcon": "el-icon-Monitor",
          "kind": "系统概述",
          "isShow": 1,
          "paths": "index",
          "menuType": "C",
          "listname": "Node",
          "tablename": "node"
        },
        {
          "menuIcon": "el-icon-Monitor",
          "kind": "云盘",
          "isShow": 1,
          "component": "article/lists/index",
          "paths": "replicaset",
          "menuType": "C",
          "listname": "apps.ReplicaSet",
          "tablename": "apps.replicaset"
        }
      ]
    },
      {
        "menuIcon": "el-icon-CollectionTag",
        "kind": "Pod",
        "isShow": 1,
        "component": "article/lists/index",
        "paths": "column",
        "menuType": "C",
        "listname": "Pod",
        "tablename": "pod"
      },
      {
        "menuIcon": "el-icon-Monitor",
        "kind": "工作负载",
        "isShow": 1,
        "paths": "/appMgr/workload",
        "menuType": "M",
        "children": [{
          "menuIcon": "el-icon-Monitor",
          "kind": "Pod",
          "isShow": 1,
          "component": "article/lists/index",
          "paths": "pod",
          "menuType": "C",
          "listname": "Pod",
          "tablename": "pod"
        }]
      }
    ]
  }
}
