---
apiVersion: "apps/v1"
kind: "Deployment"
metadata: 
  name: "kube-mirror"
  namespace: "kube-stack"
  labels: 
    name: "kube-mirror"
spec: 
  replicas: 1
  selector: 
    matchLabels:
      name: "kube-mirror"
  template: 
    metadata: 
      labels: 
        name: "kube-mirror"
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
      containers:
      - name: "kube-mirror"
        image: "registry.cn-beijing.aliyuncs.com/dosproj/mirror:v0.2.7"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: kubeRegion
          value: "local"
        command: 
        - "java"
        - "-jar"
        - "kube-mirror.jar"
        volumeMounts:
        - name: "cert"
          mountPath: "/etc/kubernetes/admin.conf"
      volumes: 
      - name: "cert"
        hostPath:
          path: /root/.kube/config
