---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "kube-frontend"
  namespace: "kube-stack"
  labels:
    name: "frontend"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "kube-frontend"
  template:
    metadata:
      labels:
        name: "kube-frontend"
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
      containers:
        - name: "kube-frontend"
          image: "g-ubjg5602-docker.pkg.coding.net/iscas-system/containers/frontend:v0.0.3"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: kube-frontend
  namespace: kube-stack
  labels:
    name: kube-frontend
spec:
  type: NodePort
  ports:
    - port: 30000
      protocol: TCP
      targetPort: 30000
      name: frontend
      nodePort: 30000
  selector:
    name: kube-frontend
